apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "225"
  name: keycert-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycert-hook-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: ssp
